### ISSUE TITLE
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SongYxing** [open-mmlab/mmediting#1024]
I use 3090 to train realbasicvsr.
 .md allows me to install cuda10.1, but cuda10.1 can only be used under sm7.5. The sm of 3090 is 8.6, which is not applicable to cuda10.1. When I use cuda11.0 for training, I will be prompted with an error: 
importerror: libcudart.so.10.1: cannot open shared object file: no such file or directory

**Comment by huang-hz** [comment]
As you can see ,3090 doesn't support cuda whose version is too early. It bring the same problem in my server and I found two ways may do help to this .
1. Install high version cuda supprted by 3090 , then install the mmcv-full referring https://github.com/open-mmlab/mmcv. After that you may meet a new  ImportError. 
2.  Install MMCV with [MIM](https://github.com/open-mmlab/mim).
pip3 install openmim
mim install mmcv-full

**Comment by SongYxing** [comment]
> As you can see ,3090 doesn't support cuda whose version is too early. It bring the same problem in my server and I found two ways may do help to this .
> 
> 1. Install high version cuda supprted by 3090 , then install the mmcv-full referring https://github.com/open-mmlab/mmcv. After that you may meet a new  ImportError.
> 2. Install MMCV with [MIM](https://github.com/open-mmlab/mim).
>    pip3 install openmim
>    mim install mmcv-full

Thanks,I have solved this error

**Comment by zengyh1900** [comment]
Closing due to inactivity, please reopen if there are any further problems.
